In [1]:
import tweepy
from tweepy import api
import datetime
import pandas as p
from tweepy import Cursor
from datetime import datetime

In [2]:
# Create variables for each key, secret, token
consumer_key = ''
consumer_secret = ''
access_token = ''
access_token_secret = ''

input_directory = "C:/Users/BLAHBLAHBLAH/Desktop/random_users.csv"
output_directory = "C:/Users/BLAHBLAHBLAH/Desktop/tweets_from_random_users.csv"

In [3]:
# Set up OAuth and integrate with API
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit = True)

In [4]:
def tweets_from_many_people(people):
    if len(people) < 2:
        return "Oops!"
    
    tweets_all = tweets_from_person(people[0])
    people.pop(0)
    
    n_person = 1
    n_people = len(people)
    for person in people:
        print("Total Tweets:  " + str(tweets_all.shape[0]))
        print("Finished Person:  " + str(n_person) + " of " + str(n_people))
        tweets_all = p.concat(
            [
                tweets_all.reset_index(drop = True),
                tweets_from_person(person)
            ],
            axis = 0
        )
        n_person = n_person + 1
    
    return tweets_all

def tweets_from_person(person):
    tweets_text = []
    tweets_date = []
    name = []
    tweets = tweepy.Cursor(
        api.user_timeline,
        id = person
    ).items(25)
    
    while True:
        try:
            tweet = next(tweets)
        except tweepy.TweepError as error:
            error_code = int(error.args[0][38:41])
            print("Error " + str(error_code))
            now = datetime.now()
            current_time = now.strftime("%I:%M")
            print("Current Time =", current_time)
            if error_code == 420:
                time.sleep(60 * 15)
                continue
            else:
                return p.DataFrame({
                    'date': tweets_date,
                    'tweets': tweets_text,
                    'name': name
                })    
        except StopIteration:
            return p.DataFrame({
                'date': tweets_date,
                'tweets': tweets_text,
                'name': name
            })
        tweets_text.append(tweet.text)
        tweets_date.append(tweet.created_at.strftime("%Y-%m-%d"))
        name.append(person)

In [5]:
data = p.read_csv(input_directory)
data.head(5)

  Random People
0       NASAJPL
1  EnglandRugby
2  BAPEOFFICIAL
3  imacelebrity
4   AlisonSudol

In [6]:
tweets = tweets_from_many_people(data.iloc[:,0])

Total Tweets:  25
Finished Person:  1 of 99
Total Tweets:  50
Finished Person:  2 of 99
Total Tweets:  75
Finished Person:  3 of 99
Total Tweets:  100
Finished Person:  4 of 99
Total Tweets:  125
Finished Person:  5 of 99
Total Tweets:  150
Finished Person:  6 of 99
Total Tweets:  175
Finished Person:  7 of 99
Total Tweets:  200
Finished Person:  8 of 99
Total Tweets:  225
Finished Person:  9 of 99
Total Tweets:  250
Finished Person:  10 of 99
Total Tweets:  275
Finished Person:  11 of 99
Total Tweets:  300
Finished Person:  12 of 99
Total Tweets:  325
Finished Person:  13 of 99
Total Tweets:  350
Finished Person:  14 of 99
Total Tweets:  375
Finished Person:  15 of 99
Total Tweets:  400
Finished Person:  16 of 99
Total Tweets:  425
Finished Person:  17 of 99
Total Tweets:  450
Finished Person:  18 of 99
Total Tweets:  475
Finished Person:  19 of 99
Total Tweets:  500
Finished Person:  20 of 99
Total Tweets:  525
Finished Person:  21 of 99
Total Tweets:  550
Finished Person:  22 of 99
Total Tweets:  575
Finished Person:  23 of 99
Total Tweets:  600
Finished Person:  24 of 99
Total Tweets:  625
Finished Person:  25 of 99
Total Tweets:  650
Finished Person:  26 of 99
Total Tweets:  675
Finished Person:  27 of 99
Total Tweets:  700
Finished Person:  28 of 99
Total Tweets:  725
Finished Person:  29 of 99
Total Tweets:  750
Finished Person:  30 of 99
Total Tweets:  775
Finished Person:  31 of 99
Total Tweets:  800
Finished Person:  32 of 99
Total Tweets:  825
Finished Person:  33 of 99
Total Tweets:  850
Finished Person:  34 of 99
Total Tweets:  875
Finished Person:  35 of 99
Total Tweets:  900
Finished Person:  36 of 99
Total Tweets:  925
Finished Person:  37 of 99
Total Tweets:  950
Finished Person:  38 of 99
Total Tweets:  975
Finished Person:  39 of 99
Total Tweets:  1000
Finished Person:  40 of 99
Total Tweets:  1025
Finished Person:  41 of 99
Total Tweets:  1050
Finished Person:  42 of 99
Total Tweets:  1075
Finished Person:  43 of 99
Total Tweets:  1100
Finished Person:  44 of 99
Total Tweets:  1125
Finished Person:  45 of 99
Total Tweets:  1150
Finished Person:  46 of 99
Total Tweets:  1175
Finished Person:  47 of 99
Total Tweets:  1200
Finished Person:  48 of 99
Total Tweets:  1225
Finished Person:  49 of 99
Total Tweets:  1250
Finished Person:  50 of 99
Total Tweets:  1275
Finished Person:  51 of 99
Total Tweets:  1300
Finished Person:  52 of 99
Total Tweets:  1325
Finished Person:  53 of 99
Total Tweets:  1350
Finished Person:  54 of 99
Total Tweets:  1375
Finished Person:  55 of 99
Total Tweets:  1400
Finished Person:  56 of 99
Total Tweets:  1425
Finished Person:  57 of 99
Total Tweets:  1450
Finished Person:  58 of 99
Total Tweets:  1475
Finished Person:  59 of 99
Total Tweets:  1500
Finished Person:  60 of 99
Total Tweets:  1525
Finished Person:  61 of 99
Total Tweets:  1550
Finished Person:  62 of 99
Total Tweets:  1575
Finished Person:  63 of 99
Total Tweets:  1600
Finished Person:  64 of 99
Total Tweets:  1625
Finished Person:  65 of 99
Total Tweets:  1650
Finished Person:  66 of 99
Total Tweets:  1675
Finished Person:  67 of 99
Total Tweets:  1700
Finished Person:  68 of 99
Total Tweets:  1725
Finished Person:  69 of 99
Total Tweets:  1750
Finished Person:  70 of 99
Total Tweets:  1775
Finished Person:  71 of 99
Total Tweets:  1800
Finished Person:  72 of 99
Total Tweets:  1825
Finished Person:  73 of 99
Total Tweets:  1850
Finished Person:  74 of 99
Total Tweets:  1875
Finished Person:  75 of 99
Total Tweets:  1900
Finished Person:  76 of 99
Total Tweets:  1925
Finished Person:  77 of 99
Total Tweets:  1950
Finished Person:  78 of 99
Total Tweets:  1975
Finished Person:  79 of 99
Total Tweets:  2000
Finished Person:  80 of 99
Total Tweets:  2025
Finished Person:  81 of 99
Total Tweets:  2050
Finished Person:  82 of 99
Total Tweets:  2075
Finished Person:  83 of 99
Total Tweets:  2100
Finished Person:  84 of 99
Total Tweets:  2125
Finished Person:  85 of 99
Total Tweets:  2150
Finished Person:  86 of 99
Total Tweets:  2175
Finished Person:  87 of 99
Total Tweets:  2200
Finished Person:  88 of 99
Total Tweets:  2225
Finished Person:  89 of 99
Total Tweets:  2250
Finished Person:  90 of 99
Total Tweets:  2275
Finished Person:  91 of 99
Total Tweets:  2300
Finished Person:  92 of 99
Total Tweets:  2325
Finished Person:  93 of 99
Total Tweets:  2350
Finished Person:  94 of 99
Total Tweets:  2375
Finished Person:  95 of 99
Total Tweets:  2400
Finished Person:  96 of 99
Total Tweets:  2425
Finished Person:  97 of 99
Total Tweets:  2450
Finished Person:  98 of 99
Total Tweets:  2475
Finished Person:  99 of 99

In [7]:
tweets.to_csv(output_directory, index = False)