In [1]:
import pandas as p
from nltk.corpus import subjectivity
from nltk.sentiment import SentimentAnalyzer
from textblob import TextBlob
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
input_directory1 = "C:/Users/BLAHBLAHBLAH/Desktop/tweets_from_seanhannity_followers_cleaned.csv"
input_directory2 = "C:/Users/BLAHBLAHBLAH/Desktop/tweets_from_maddow_followers_cleaned.csv"

person1 = "Sean Hannity"
person2 = "Rachel Maddow"

In [3]:
data_a = p.read_csv(input_directory1, dtype = {'tweets': str})
data_a.head(5)

         date                                             tweets          name
0  2020-05-23  spain one of europes hardest hit coronavirus h...  PosCovidNews
1  2020-05-23  the us could finally be free of the coronaviru...  PosCovidNews
2  2020-05-22  white house economists say the third quarter o...  PosCovidNews
3  2020-05-22  in what researchers are heralding as a milesto...  PosCovidNews
4  2020-05-22  more good news this time from the milwaukee br...  PosCovidNews

In [4]:
data_a0 = data_a
data_a0.tweets = data_a.tweets.apply(str)
data_a0.head(5)

         date                                             tweets          name
0  2020-05-23  spain one of europes hardest hit coronavirus h...  PosCovidNews
1  2020-05-23  the us could finally be free of the coronaviru...  PosCovidNews
2  2020-05-22  white house economists say the third quarter o...  PosCovidNews
3  2020-05-22  in what researchers are heralding as a milesto...  PosCovidNews
4  2020-05-22  more good news this time from the milwaukee br...  PosCovidNews

In [5]:
data_b = p.read_csv(input_directory2, dtype = {'tweets': str})
data_b.head(5)

         date                                             tweets          name
0  2017-02-11         rayban sunglasses valentines day specials     amaldiallo
1  2014-02-13                                           you rock    amaldiallo
2  2012-02-23                                         weird mood    amaldiallo
3  2020-05-19  some of us depend on the drug to live a normal...  taheownwoman
4  2020-05-19  those of us who depend on the drug to live a n...  taheownwoman

In [6]:
data_b0 = data_b
data_b0.tweets = data_b.tweets.apply(str)
data_b0.head(5)

         date                                             tweets          name
0  2017-02-11         rayban sunglasses valentines day specials     amaldiallo
1  2014-02-13                                           you rock    amaldiallo
2  2012-02-23                                         weird mood    amaldiallo
3  2020-05-19  some of us depend on the drug to live a normal...  taheownwoman
4  2020-05-19  those of us who depend on the drug to live a n...  taheownwoman

In [7]:
data_both = p.DataFrame({
    'name': [person1, person2],
    'tweets_all': [" ".join(data_a0.tweets), " ".join(data_b0.tweets)]
})
data_both.head(5)

            name                                         tweets_all
0   Sean Hannity  spain one of europes hardest hit coronavirus h...
1  Rachel Maddow  rayban sunglasses valentines day specials  you...

In [8]:
cv = CountVectorizer(stop_words = 'english')
data_cv = cv.fit_transform(data_both.tweets_all)
data_dtm = p.DataFrame(
    data_cv.toarray(),
    columns = cv.get_feature_names()
)
data_dtm.index = data_both.name
#data2_dtm.to_pickle('dtm.pkl')
data_dtm = data_dtm.transpose()
data_dtm.head(5)

name         Sean Hannity  Rachel Maddow
aa                      9              4
aaa                     3              0
aaaa                    1              0
aaaaaaaa                0              1
aaaaaaaaaaa             1              0

In [9]:
data_vocabulary_comparison = p.DataFrame({
    'word_ratio': data_dtm.iloc[:,0]/data_dtm.iloc[:,1],
    'word_difference': data_dtm.iloc[:,0] - data_dtm.iloc[:,1],
    'count_Republicans': data_dtm.iloc[:,0],
    'count_Democrats': data_dtm.iloc[:,1]
})

In [10]:
data_vocabulary_comparison.sort_values(by = ['word_ratio', 'word_difference']).query(
    'count_Democrats > 24 & count_Republicans > 0'
).iloc[0:60,]

             word_ratio  word_difference  count_Republicans  count_Democrats
tump           0.018868              -52                  1               53
violated       0.053571              -53                  3               56
chip           0.054054              -35                  2               37
golfs          0.073171              -38                  3               41
detention      0.074074              -25                  2               27
mcconnell      0.089286              -51                  5               56
devastating    0.090909              -40                  4               44
maddow         0.115385              -23                  3               26
colleagues     0.117647              -30                  4               34
capita         0.120000              -22                  3               25
equality       0.120000              -22                  3               25
donation       0.151515              -28                  5               33
safer          0.152174              -39                  7               46
merci          0.160000              -21                  4               25
lindsey        0.174603              -52                 11               63
universal      0.184211              -31                  7               38
mitch          0.193548              -50                 12               62
golfing        0.194444              -87                 21              108
asks           0.205882              -27                  7               34
che            0.206897              -23                  6               29
warnings       0.206897              -23                  6               29
bleach         0.212766              -37                 10               47
ahmaud         0.214286              -22                  6               28
selfish        0.218750              -25                  7               32
eligible       0.225806              -24                  7               31
publicly       0.230769              -20                  6               26
putin          0.230769              -20                  6               26
som            0.230769              -20                  6               26
terrorism      0.230769              -20                  6               26
ms             0.232558              -33                 10               43
assistant      0.233333              -23                  7               30
cummings       0.243243              -28                  9               37
ignored        0.243243              -28                  9               37
writing        0.244444              -34                 11               45
der            0.250000              -36                 12               48
dominic        0.250000              -21                  7               28
struggling     0.250000              -21                  7               28
inspiration    0.259259              -20                  7               27
lessons        0.259259              -20                  7               27
webinar        0.259259              -20                  7               27
bots           0.263158              -28                 10               38
trumps         0.266447             -223                 81              304
graham         0.266667              -44                 16               60
adequate       0.266667              -22                  8               30
strategy       0.271186              -43                 16               59
presidency     0.276596              -34                 13               47
threatened     0.281250              -23                  9               32
quality        0.285714              -50                 20               70
likely         0.288136              -42                 17               59
warren         0.290323              -22                  9               31
incredibly     0.294118              -24                 10               34
cult           0.296296              -19                  8               27
tara           0.296296              -19                  8               27
gop            0.300000              -84                 36              120
resign         0.302326              -30                 13               43
basic          0.303030              -23                 10               33
viruses        0.303030              -23                 10               33
reaching       0.305085              -41                 18               59
artist         0.312500              -33                 15               48
zoom           0.312500              -22                 10               32

In [11]:
data_vocabulary_comparison.sort_values(by = ['word_ratio', 'word_difference'], ascending = False).query(
    'count_Republicans > 25 & count_Democrats > 0'
).iloc[0:60,]

,word_ratio,word_difference,count_Republicans,count_Democrats
bolsonaroreeleito,41.000000,40,41,1
xrp,29.000000,28,29,1
ccp,17.333333,49,52,3
heisman,15.250000,57,61,4
nissanusa,14.000000,26,28,2
patriots,11.555556,95,104,9
playlist,11.500000,63,69,6
fakenews,11.333333,31,34,3
omar,11.250000,41,45,4
msm,10.250000,37,41,4
गर,10.000000,63,70,7
ilhan,9.000000,32,36,4
venezuelan,9.000000,24,27,3
sleepy,7.444444,58,67,9
youaintblack,7.000000,90,105,15
fearless,6.750000,23,27,4
gretchen,6.750000,23,27,4
nbssnl,6.750000,23,27,4
coup,6.500000,22,26,4
earned,5.700000,47,57,10
prosecuted,5.600000,23,28,5
steam,5.600000,23,28,5
communist,5.500000,54,66,12
daddy,5.363636,48,59,11
figuring,5.200000,21,26,5
gemini,5.200000,21,26,5
mainstream,5.166667,25,31,6
counts,5.142857,29,36,7
उन,5.142857,29,36,7
pennsylvania,5.000000,36,45,9
biafra,5.000000,24,30,6
पह,5.000000,24,30,6
joebiden,4.909091,43,54,11
testimony,4.833333,23,29,6
terrorists,4.666667,22,28,6
wuhan,4.500000,21,27,6
बस,4.500000,21,27,6
हम,4.444444,31,40,9
हर,4.375000,27,35,8
obamagate,4.347222,241,313,72
nursing,4.344828,97,126,29
sweepstakes,4.333333,30,39,9
parenthood,4.333333,20,26,6
जन,4.333333,20,26,6
dems,4.259259,88,115,27
liberals,4.250000,39,51,12
funded,4.142857,22,29,7
inviting,4.142857,22,29,7
به,4.125000,25,33,8
beating,4.090909,34,45,11
sugar,4.066667,46,61,15
qanon,4.000000,48,64,16
schiff,4.000000,30,40,10
comey,4.000000,27,36,9
desk,4.000000,21,28,7
نے,4.000000,21,28,7
amen,3.933333,132,177,45
greatness,3.923077,38,51,13
wolf,3.875000,23,31,8
hai,3.866667,43,58,15